# Generated by Django 6.0.3 on 2026-03-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_Name', models.CharField(max_length=256)),
                ('Business_Balance', models.FloatField(default=0.0)),
                ('Business_Profile', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_FName', models.CharField(max_length=256)),
                ('User_LName', models.CharField(max_length=256)),
                ('User_IsSiteAdmin', models.BooleanField(default=False)),
                ('User_IsEmployed', models.BooleanField(default=False)),
                ('User_Balance', models.FloatField(default=0.0)),
                ('User_Password', models.CharField(max_length=256)),
                ('User_BirthDate', models.DateField()),
                ('User_Email', models.CharField(max_length=256)),
                ('User_Profile', models.CharField(max_length=256)),
            ],
        ),
    ]
