# Generated by Django 6.0.3 on 2026-04-23 21:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterParty',
            fields=[
                ('CounterParty_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Expense_Title', models.CharField(max_length=256)),
                ('Expense_Type', models.CharField(max_length=256)),
                ('Description', models.CharField(max_length=256)),
                ('Expense_Date_Issued', models.DateField(auto_now_add=True)),
                ('Expense_Due_By', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Individual_Balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Individual_BirthDate', models.DateField()),
                ('Individual_Profile', models.CharField(max_length=256)),
                ('Individual_PhoneNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('User_Role', models.CharField(choices=[('INDIVIDUAL', 'Individual Client'), ('BUSINESS', 'Business Client'), ('BUSINESS_ADMIN', 'Business Admin'), ('SITE_ADMIN', 'Site Admin'), ('EMPLOYEE', 'Employee')], default='INDIVIDUAL', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('Business_ID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('Business_Name', models.CharField(max_length=256)),
                ('Business_Balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Business_Profile', models.CharField(blank=True, max_length=256)),
                ('Business_PhoneNumber', models.CharField(max_length=20)),
                ('Admin_Email', models.CharField(max_length=256)),
                ('Business_AccessCode', models.CharField(blank=True, max_length=6, unique=True)),
                ('User_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business_Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_admin', to='api.business')),
                ('User_ID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_ID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_client', to='api.business')),
                ('CounterParty_ID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_client', to='api.counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.PositiveIntegerField(default=1)),
                ('Name', models.CharField(max_length=64)),
                ('Terms', models.CharField(max_length=5000)),
                ('Business_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.business')),
                ('CounterParty_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.counterparty')),
                ('Expense_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='api.expense')),
            ],
        ),
        migrations.CreateModel(
            name='Expense_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_Title', models.CharField(max_length=256)),
                ('Expense_Plan_Due', models.DateField()),
                ('Business_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_plans', to='api.business')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='Expense_Plan_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.expense_plan'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Role', models.CharField(max_length=64)),
                ('Business_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.business')),
                ('Expense_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='api.expense')),
                ('Expense_Plan_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.expense_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Individual_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CounterParty_ID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indiv_client', to='api.counterparty')),
                ('User_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indiv_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_Frequency', models.CharField(max_length=64)),
                ('Occurance_Number', models.PositiveIntegerField(default=1)),
                ('Expense_Plan_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_plans', to='api.expense_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Site_Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moderates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderates', to='api.business')),
                ('Site_Admin_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderates', to='api.site_admin')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_Date', models.DateField(auto_now_add=True)),
                ('Business_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.business')),
                ('User_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Has_Paid', models.BooleanField(default=False)),
                ('Policy_Description', models.CharField(max_length=256)),
                ('CounterParty_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='api.counterparty')),
                ('Transaction_ID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='api.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Expense_Pay_Off',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Expense_ID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_pay_off', to='api.expense')),
                ('Transaction_ID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_pay_off', to='api.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Line_Number', models.PositiveIntegerField()),
                ('Cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Description', models.CharField(max_length=256)),
                ('Quantity', models.PositiveIntegerField(default=1)),
                ('Header', models.CharField(max_length=256)),
                ('Invoice_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_line_items', to='api.invoice')),
            ],
            options={
                'unique_together': {('Invoice_ID', 'Line_Number')},
            },
        ),
    ]
