# Generated by Django 6.0.3 on 2026-04-07 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterParty',
            fields=[
                ('CounterParty_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost', models.FloatField(default=0.0)),
                ('Expense_Type', models.CharField(max_length=256)),
                ('Description', models.CharField(max_length=256)),
                ('Expense_Date_Issued', models.DateField(auto_now_add=True)),
                ('Expense_Due_By', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='business',
            name='Business_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='User_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Business_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.business')),
                ('User_ID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Business_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_ID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.business')),
                ('CounterParty_ID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('Contract_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Duration', models.PositiveIntegerField(default=1)),
                ('Name', models.CharField(max_length=64)),
                ('Terms', models.CharField(max_length=5000)),
                ('Business_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.business')),
                ('CounterParty_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.counterparty')),
                ('Expense_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.expense')),
            ],
        ),
        migrations.CreateModel(
            name='Expense_Plan',
            fields=[
                ('Expense_Plan_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Plan_Title', models.CharField(max_length=256)),
                ('Expense_Plan_Due', models.DateField()),
                ('Business_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.business')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='Expense_Plan_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.expense_plan'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Pay', models.FloatField(default=0.0)),
                ('Role', models.CharField(max_length=64)),
                ('Business_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.business')),
                ('User_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('Expense_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.expense')),
                ('Expense_Plan_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.expense_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Individual_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CounterParty_ID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.counterparty')),
                ('User_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Has_Paid', models.BooleanField(default=False)),
                ('Policy_Description', models.CharField(max_length=256)),
                ('CounterParty_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Line_Number', models.PositiveIntegerField(unique=True)),
                ('Cost', models.FloatField(default=0.0)),
                ('Description', models.CharField(max_length=256)),
                ('Quantity', models.PositiveIntegerField(default=1)),
                ('Header', models.CharField(max_length=256)),
                ('Invoice_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_Frequency', models.CharField(max_length=64)),
                ('Occurance_Number', models.PositiveIntegerField(default=1)),
                ('Expense_Plan_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expense_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Site_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Moderates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.business')),
                ('Site_Admin_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.site_admin')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('Transaction_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Transaction_Date', models.DateField(auto_now_add=True)),
                ('Business_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.business')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Expense_Pay_Off',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Pay', models.FloatField(default=0.0)),
                ('Expense_ID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.expense')),
                ('Transaction_ID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.transaction')),
            ],
        ),
    ]
